/*
 * Album Store API
 *
 * CS6650 Fall 2023
 *
 * API version: 1.0.0
 * Contact: i.gorton@northeasern.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"strconv"
	"sync"
)

type AlbumsService struct {
	albumInfos map[string]AlbumInfo
	albumId    int
	mu         sync.RWMutex
}

func NewAlbumsService() *AlbumsService {
	return &AlbumsService{
		albumInfos: make(map[string]AlbumInfo),
		albumId:    1,
	}
}

func (s *AlbumsService) GetAlbumByKey(albumId string) (AlbumInfo, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	album, ok := s.albumInfos[albumId]
	return album, ok
}

func (s *AlbumsService) PostNewAlbum(albumInfo AlbumInfo) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	newAlbumId := strconv.Itoa(s.albumId)
	s.albumInfos[newAlbumId] = albumInfo
	s.albumId++
	return newAlbumId
}
